[browser]
gatherUsageStats = true
serverAddress = "0.0.0.0"
serverPort = 8888
[server]
port = 8888
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "AE00AD"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#ededed"
textColor = "#242424"
font = "monospace"
